title: Terminal

env:
  TERM: xterm-256color

window:
  dimensions:
    columns: 100
    lines: 55
  padding:
    x: 0
    y: 0
  decorations: buttonless
  title: Terminal
  option_as_alt: OnlyLeft # other values are None, OnlyRight, Both

# Colors (Nord)
colors:
  # Default colors
  primary:
    background: "0x2e3440"
    foreground: "0xd8dee9"

  # Cursor colors
  cursor:
    text: "0x272727"
    cursor: "0xeceff4"

  # Normal colors
  normal:
    black: "0x3b4252"
    red: "0xbf616a"
    green: "0xa3be8c"
    yellow: "0xebcb8b"
    blue: "0x81a1c1"
    magenta: "0xb48ead"
    cyan: "0x88c0d0"
    white: "0xe5e9f0"

  # Bright colors
  bright:
    black: "0x4c566a"
    red: "0xbf616a"
    green: "0xa3be8c"
    yellow: "0xebcb8b"
    blue: "0x81a1c1"
    magenta: "0xb48ead"
    cyan: "0x8fbcbb"
    white: "0xeceff4"

font:
  # family: Fantasque Sans Mono
  normal:
    family: Source Code Pro for Powerline
    style: Regular
  bold:
    family: Source Code Pro for Powerline
    style: Medium

  size: 18
