#!/usr/bin/env bash

# used by macos-bootstrap. see https://github.com/karstenmueller/macos-bootstrap/blob/main/modules/dotfiles.sh
# will be executed by GitHub codesoaces if you choose so, see "Automatically install dotfiles" in https://github.com/settings/codespaces

set -o nounset -o errexit -o pipefail

pushd "$(dirname "${BASH_SOURCE[0]}")/../" >/dev/null

echo "--> linking dotfiles in $(pwd) to $HOME/"a
while IFS= read -r -d '' i; do
    test -f "$(pwd)/$i" &&
        ln -sf "$(pwd)/$i" "$HOME"/
done < <(find . -type f -name '.[a-zA-Z]*' -print0)

echo "--> linking $(pwd)/.oh-my-zsh/custom to $HOME/.oh-my-zsh/custom"
for subdir in plugins themes; do
    mkdir -p "$HOME/.oh-my-zsh/custom/$subdir"
    pushd ".oh-my-zsh/custom/$subdir" >/dev/null
    ln -sf "$(pwd)"/* "$HOME/.oh-my-zsh/custom/$subdir"
    popd >/dev/null
done

# create some required directories
install -d -m 700 ~/.ssh ~/.local

if [ "$(uname)" == "Darwin" ]; then
    # defaults Location for Screenshots
    defaults write com.apple.screencapture location ~/Downloads
    # defaults Autohide Dock
    defaults write com.apple.dock autohide -bool true
    # iTerm shell integration
    curl -Ls https://iterm2.com/shell_integration/install_shell_integration_and_utilities.sh | bash
fi

echo "--> FINISHED"
