#!/usr/bin/env bash

set -o nounset -o errexit -o pipefail

# make files in ~/.dotfiles available
echo "--> linking ~/.dotfiles to $HOME/"
pushd ~/.dotfiles >/dev/null
# for i in $(find . -type f -name '.[a-zA-Z]*'); do
#     test -f "$(pwd)/$i" &&
#         ln -sf "$(pwd)/$i" "$HOME"/
# done
while IFS= read -r -d '' i; do
    test -f "$(pwd)/$i" &&
        ln -sf "$(pwd)/$i" "$HOME"/
done < <(find . -type f -name '.[a-zA-Z]*' -print0)
popd >/dev/null

echo "--> linking .dotfiles/.oh-my-zsh/custom to .oh-my-zsh/custom"
for subdir in plugins themes; do
    mkdir -p "$HOME/.oh-my-zsh/custom/$subdir"
    pushd "$HOME"/.dotfiles/.oh-my-zsh/custom/$subdir >/dev/null
    ln -sf "$(pwd)"/* "$HOME/.oh-my-zsh/custom/$subdir"
done
popd >/dev/null

mkdir -p "$HOME/.local"

## create SSH directory
install -d -m 700 ~/.ssh

if [ "$(uname)" == "Darwin" ]; then
    # defaults Location for Screenshots
    defaults write com.apple.screencapture location ~/Downloads
    # defaults Autohide Dock
    defaults write com.apple.dock autohide -bool true
    # iTerm shell integration
    curl -Ls https://iterm2.com/shell_integration/install_shell_integration_and_utilities.sh | bash
fi

echo "--> FINISHED"
